### ISSUE TITLE
Boolean Flags not supported with *args/**kwargs

### ISSUE THREAD

**Issue by yonromai** [haydenflinner/magicinvoke#1]
First of all, thanks @haydenflinner for your work - wish the kwargs support would be part of native invoke!

Perhaps I'm missing something but it seems that valueless (boolean) flags don't work out of the box:
```
inv my-task --foo
```
Fails with `Flag <Argument: foo> needed value and was not given one!`

But:
```
inv my-task --foo bar
```
works as `{"foo": "bar"}` ends up in `kwargs`.

**Comment by haydenflinner** [comment]
Thanks so much for the support!
Also good idea, added! You can try master if you want or I can just push it to pip, it didn't break any tests that should have broken

#8788dc31d05d083815bd65f80cbd21fbaf4f84ce

**Comment by yonromai** [comment]
Seems to be working indeed! Thanks a lot for the quick fix!
