### ISSUE TITLE
ImportError: cannot import name 'Iterable' from 'collections'

### ISSUE THREAD

**Issue by jock-tanner** [haydenflinner/magicinvoke#6]
This error prevented me from using MagicInvoke with Python 2.8 and up.

I've made a PR for this: https://github.com/haydenflinner/magicinvoke/pull/5 . Would you please review and merge.

Otherwise MagicInvoke works fine for me (Python 3.10). So far I'm using only task kwargs though. Anyway, big thankyou to the contributors. Such a useful package.

**Comment by haydenflinner** [comment]
Awesome, glad you're enjoying the repo! Merged. Will trust ya that it works because for some reason Travis is refusing to cooperate. At least it works on my local box. Released as a patch.
